name: Greeting
# on: push
on:
    push:
        branches:
            - main
            - 'feature/**'
jobs:
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: "greet user"
              run: echo "Hello world!"
